### ISSUE TITLE
RealGud integration

### ISSUE THREAD

**Issue by Pitometsu** [pwalsh/pipenv.el#10]
Check is [RealGud](https://github.com/realgud/realgud) able to find several python debuggers like `ipdb` in `pipenv` path.

**Comment by pwalsh** [comment]
`pipenv.el` now pushes the virtual env path to `(exec-path)` when a pipenv-managed project is activated, for example by `(pipenv-activate)`.

- https://github.com/pwalsh/pipenv.el/blob/master/pipenv.el#L163
- https://github.com/pwalsh/pipenv.el/blob/master/pipenv.el#L327
- https://github.com/pwalsh/pipenv.el/blob/master/test/pipenv-test.el#L31

This should be enough for `RealGud` to find any executable it expects.

**Comment by Pitometsu** [comment]
Confirm, thank you.
