### ISSUE TITLE
Py.Test integration

### ISSUE THREAD

**Issue by Pitometsu** [pwalsh/pipenv.el#11]
Check is [Py.Test](https://github.com/ionrock/pytest-el) able to work with `pipenv` out of the box (locate `pytest` executable).

**Comment by pwalsh** [comment]
`pipenv.el` now pushes the virtual env path to `(exec-path)` when a pipenv-managed project is activated, for example by `(pipenv-activate)`.

- https://github.com/pwalsh/pipenv.el/blob/master/pipenv.el#L163
- https://github.com/pwalsh/pipenv.el/blob/master/pipenv.el#L327
- https://github.com/pwalsh/pipenv.el/blob/master/test/pipenv-test.el#L31

This should be enough for `Py.Test` to find any executable it expects.

**Comment by Pitometsu** [comment]
`M-x pytest-all`
```
-*- mode: compilation; default-directory: "~/Projects/csr/csr/ic/" -*-
Comint started at Fri Feb 16 12:07:02

cd '/Users/netsu/Projects/csr/csr/ic/' && pytest -s -v --pdb --pdbcls=IPython.terminal.debugger:Pdb ''.''
/usr/local/bin/bash: pytest: command not found

Inferior Python exited abnormally with code 127 at Fri Feb 16 12:07:02
```
And in \*Messages\*:
```
Inferior Python exited abnormally with code 127
pytest-run: Symbol’s value as variable is void: python-shell--interpreter
```

**Comment by Pitometsu** [comment]
My setup:
```elisp
 '(pytest-cmd-flags "-s -v --pdb --pdbcls=IPython.terminal.debugger:Pdb")
 '(pytest-global-name "pytest")
 '(pytest-project-root-files (quote ("setup.py" ".hg" ".git" "Pipfile" "tests")))
```
Is it work for you? Or this issue irrelevant to `pipenv`, and should be targeted to `pytest` directly, is it?

**Comment by pwalsh** [comment]
pipenv doesn’t touch python-shell-interpreter and you have a weird error about python-shell—interpreter, suggesting some wrong in your config.

**Comment by Pitometsu** [comment]
@pwalsh I fixed `pytest-run: Symbol’s value as variable is void: python-shell--interpreter`
by

```elisp
(defvar python-shell--interpreter python-shell-interpreter)
(defvar python-shell--interpreter-args python-shell-interpreter-args)
```

Not sure, is it Emacs bug, and should I report it (I have no python-shell-whatever anywhere in configuration before).

According to `pipenv`: `pytest` still tell me `/usr/local/bin/bash: pytest: command not found` unless I set it up manually:

```elisp
'(pytest-global-name "pipenv run pytest")
```

and in that case it works.
