### ISSUE TITLE
Fix eldoc for custom python-shell-interpreter

### ISSUE THREAD

**Issue by Pitometsu** [pwalsh/pipenv.el#12]
With

```elisp
'(python-shell-interpreter "ipython")
```
There's error:
```
eldoc error: (file-error Searching for program No such file or directory ipython)
```
In \*Messages\*.

**Comment by pwalsh** [comment]
@Pitometsu 

If `python-shell-interpreter` is `"ipython"`, it seems unlikely that you are in a virtual environment being managed by Pipenv, as if it were, there would be a value like `/Users/netsu/.local/share/virtualenvs/csr-44kfYsMA/bin/python`.

Did you add `"ipython"` manually? Maybe, as I [wrote here](https://github.com/pwalsh/pipenv.el/issues/8#issuecomment-359254860) you want `pipenv.el` to use an `ipython` executable as the `python-shell-interpreter` from the active virtual environment, if such an executable exists?

**Comment by Pitometsu** [comment]
It would be nice, if `pipenv` remember original (customized by user) `python-shell-interpreter` value, and would try to call it from environment. But proposed approach ok for me.

**Comment by pwalsh** [comment]
`pipenv.el` no longer modifies `python-shell-interpreter`, so user settings are respected for this variable.

`pipenv.el` now pushes the virtual env path to `(exec-path)` when a pipenv-managed project is activated, for example by `(pipenv-activate)`.

- https://github.com/pwalsh/pipenv.el/blob/master/pipenv.el#L163
- https://github.com/pwalsh/pipenv.el/blob/master/pipenv.el#L327
- https://github.com/pwalsh/pipenv.el/blob/master/test/pipenv-test.el#L31
