### ISSUE TITLE
Flycheck integration doesn't work?

### ISSUE THREAD

**Issue by mssdvd** [pwalsh/pipenv.el#14]
Hello, 
Projectile integration does not work to me. I have to activate pipenv manually. In addition, to activate flycheck integration I have to close the file and reopen it.
Here is my configuration:

```emacs

;; projectile
;; https://github.com/bbatsov/projectile
(use-package projectile
  :delight '(:eval (concat " " (projectile-project-name)))
  :defer 1
  :init (setq projectile-keymap-prefix (kbd "<menu>"))
  :config
  (projectile-mode)
  (add-to-list 'projectile-project-root-files "platformio.ini")
  (setq projectile-completion-system 'ivy
		projectile-enable-caching t
		projectile-track-known-projects-automatically nil
		projectile-files-cache-expire 2592000))


;; flycheck
;; http://www.flycheck.org
;; Dep pylint, clang, tidy, csslint
(use-package flycheck
  :defer 1
  :bind (:map flycheck-mode-map ("C-c ! !" . hydra-flycheck/body))
  :config
  (global-flycheck-mode)
  (setq-default flycheck-global-modes '(not org-mode)
                flycheck-disabled-checkers '(python-flake8))
  (defhydra hydra-flycheck
    (:pre (progn (setq hydra-lv t) (flycheck-list-errors))
          :post (progn (setq hydra-lv nil) (quit-windows-on "*Flycheck errors*"))
          :hint nil)
    "Errors"
    ("f"  flycheck-error-list-set-filter  "Filter")
    ("n"  flycheck-next-error             "Next")
    ("p"  flycheck-previous-error         "Previous")
    ("q"  nil                             "Quit")))


;; pipenv.el
;; https://github.com/pwalsh/pipenv.el
;; Dep pipenv
(use-package pipenv
  :hook (python-mode . pipenv-mode)
  :config
  (setq pipenv-projectile-after-switch-function #'pipenv-projectile-after-switch-extended))


```

**Comment by pwalsh** [comment]
@mssdvd thanks for the report. Can you please let me know if `pipenv.el` logs anything to `*Messages*` and `*Pipenv*` when switching projects with Projectile.

**Comment by mssdvd** [comment]
The buffer *pipenv* does not exist and in *messages* there is nothing.

**Comment by pwalsh** [comment]
@mssdvd Can you try to set the vars in init. This is how I do it and it works:

```
(use-package pipenv
  :hook (python-mode . pipenv-mode)
  :init
  (setq
   pipenv-projectile-after-switch-function
   #'pipenv-projectile-after-switch-extended))
```

**Comment by mssdvd** [comment]
It's the same.

**Comment by pwalsh** [comment]
Does your projectile project have a `Pipfile`? `pipenv.el` checks for it before activating:

- https://github.com/pwalsh/pipenv.el/blob/master/pipenv.el#L350
- https://github.com/pwalsh/pipenv.el/blob/master/pipenv.el#L330

**Comment by mssdvd** [comment]
I just discovered this: https://github.com/bbatsov/projectile/issues/978

**Comment by mssdvd** [comment]
However, I still have problems with flycheck integration. I manually disabled flake8 to use pylint which is installed with pipenv. The first time I open the project I get this:
![image](https://user-images.githubusercontent.com/18464329/35976952-fb432654-0ce1-11e8-9b93-f36de54d8f0a.png)
So flycheck chooses pycompile.
When I open the project for the second time, flycheck chooses pylint.
![image](https://user-images.githubusercontent.com/18464329/35976979-140b3d52-0ce2-11e8-8ebb-f4b30a853892.png)

**Comment by pwalsh** [comment]
@mssdvd 

Ok, so projectile integration does work for you now - correct?

On Flycheck, `pipenv.el` does no thing that would change Flycheck's settings around disabling a linter, yet your first screenshot shows `pylint` is disabled by Flycheck. In each case, the executable is found though, which is what `pipenv.el` does manage.

**Comment by mssdvd** [comment]
Yeah, it works.

**Comment by pwalsh** [comment]
Thanks.
