### ISSUE TITLE
pipenv-activate hanging

### ISSUE THREAD

**Issue by jackkamm** [pwalsh/pipenv.el#16]
Calling `pipenv-activate` will often hang my emacs indefinitely. I started noticing this when I last updated a week or 2 ago.

I believe the problem is a race condition in `pipenv--force-wait`, if the process finishes before the sentinel is set then it will never be called.

A reliable way to reproduce this problem is to add a `sit-for` at the top of `pipenv--force-wait`, so that the process finishes before the sentinel is set. Then the sentinel is never called and we get stuck in the infinite while loop.

**Comment by pwalsh** [comment]
Nasty! I'll check it out ( or, happy to accept a PR ;) )

**Comment by pwalsh** [comment]
Fixed in https://github.com/pwalsh/pipenv.el/pull/17
