### ISSUE TITLE
Activating the pipenv sometimes hangs

### ISSUE THREAD

**Issue by brettatoms** [pwalsh/pipenv.el#25]
Sometimes `(pipenv-activate)` hangs.  It appears to happen in the `(pipenv--force-wait (pipenv-venv))` call.  The while loop in `pipenv--force-wait` spins forever when it happens but it doesn't always happen.  At first it appears that emacs locks up but I can get back control with a `C-g`.  I put a `(message "waiting...")` in that loop and that seemed to fix it or at least caused it to happen less often so it feels kind of like a race condition.

**Comment by pwalsh** [comment]
Hi there @brettatoms 

This commit was a fix for such. race condition https://github.com/pwalsh/pipenv.el/commit/cee6bc54303314e85e0739d2fc393903933ae3cb

Can you please let me know which version of `pipenv.el` you are running?

**Comment by brettatoms** [comment]
I am running the latest in melpa which is commit 8298daefee1b044c58390c861a6a70937cb0601b

**Comment by weepingcheese** [comment]
Hey @pwalsh, thanks for pipenv.el!

I have been experiencing the race condition/hang on activate as well, happening about 1/10 times. It looks like I'm on 8298dae as well (spacemacs develop branch). I was able to make it happen consistently by reducing the sit-for time in the pipenv--force-wait function from 0.1 to 0.01. Increasing to 1.0 or whatever (making it very large doesn't seem to have any adverse effect... the sit-for returns when the process finishes, maybe?) seemed to make the race condition less likely to occur.

But that was all on my work computer (maybe relevant that it is OSX, but not at all sure). Now I'm home I can't reproduce the hang.

**Comment by SirJls** [comment]
I encountered this bug as well

**Comment by pwalsh** [comment]
hey @SirJls can you provide some details on when this occurs.

**Comment by brettatoms** [comment]
@pwalsh This happens to me almost daily.   It usually seems to happen when I switch between files in different projects with different pipenv environments so pipenv.el as activated when the projectile project changes.  Usually I can hit Ctrl-G to cancel it and then call `pipenv-activate` directly and it works fine.  But it doesn't happen every time so it seems like a race condition.

**Comment by pwalsh** [comment]
@brettatoms cool. I've tried to reproduce with tests and in usage myself and have not. I will look at it when I can, but also happy for contributions.

**Comment by brettatoms** [comment]
@pwalsh If I can come up with a reliable fix I'll definitely submit a PR.  Also, I'm using Spacemacs development branch if that helps anyone else reproduce the problem.

**Comment by pwalsh** [comment]
https://github.com/pwalsh/pipenv.el/issues/45
