### ISSUE TITLE
pipenv.el bombs *Messages* and blocks minibuffer

### ISSUE THREAD

**Issue by valignatev** [pwalsh/pipenv.el#29]
Hi, when I'm installing (or uninstalling) packages, pipenv.el bombs minbuffer and `*Messages*` buffer with status messages, effectively blocking me from using another `M-x` commands for a while (10 seconds easily).
Samples from `*Messages*`:
After installing:
```
Finished pipenv install --dev pylint objgraph [18 times]
Reverting buffer ‘Pipfile’.
Finished pipenv install --dev pylint objgraph [52 times]
Reverting buffer ‘Pipfile’.
Finished pipenv install --dev pylint objgraph [8 times]
```
After uninstalling:
```
Finished pipenv uninstall pylint objgraph [2 times]
Reverting buffer ‘Pipfile’.
Finished pipenv uninstall pylint objgraph [5 times]
Reverting buffer ‘Pipfile’.
Finished pipenv uninstall pylint objgraph [2 times]
```

**Comment by pwalsh** [comment]
I changed the use of "spam" in the title to the less controversial "bombs" which you used in the issue body @valignatev 

I have not noticed a lock up of 10 + seconds on this.

Definitely happy for a PR to improve.

**Comment by valignatev** [comment]
Sure, sorry for controversy :)
It's not strictly "blocks" like in synchronous UI call. It allows to open M-x prompt, but it overrides shadows what I type with "Finished pipenv uninstall..." message. 
An analogy of what happens is when you're trying to type something in the terminal while other process prints something to the same stdout.

Point about PR to improve taken :)

**Comment by pwalsh** [comment]
@valignatev ah I see. great, yeah I understand better now.

I'll try to get to this, but I have a few outstanding issues to work on stability of the lib, and I am trying to clear myself 1/2 a day to work on them.

Happy for any help I can get so that this library is stable for a wider community of users :).

**Comment by pwalsh** [comment]
https://github.com/pwalsh/pipenv.el/issues/45
