### ISSUE TITLE
Shell spawned by pipenv shell prints issued command before command output

### ISSUE THREAD

**Issue by giuscri** [pwalsh/pipenv.el#35]
See how a `ls -la` is printed before the actual command output.
```
(thesis-W6OBZlR6) [g@x220 thesis]$ ls -la
ls -la
total 156
drwxr-xr-x 10 g g  4096 Jul 18 17:44 .
drwx------ 25 g g  4096 Jul 18 19:41 ..
-rw-r--r--  1 g g  2226 Jul 14 17:15 attacks.py
drwxr-xr-x  2 g g  4096 Jul 16 12:02 bin
-rw-r--r--  1 g g    21 Jun 12 02:59 .coveragerc
-rw-r--r--  1 g g    46 Jun 10 11:51 .coveralls.yml
-rw-r--r--  1 g g  2330 Jul 15 12:18 datasets.py
-rw-r--r--  1 g g   533 Jun 15 00:20 Dockerfile
...
```

**Comment by giuscri** [comment]
This would be magically solved by using `term` instead of `shell`
https://github.com/pwalsh/pipenv.el/blob/822150b56c1ab481d0c4e7e87a9a189539259ed8/pipenv.el#L322
In fact you can reproduce the error by spawning a shell via `M-x shell` then issuing `$ pipenv shell` from there; you can't if you use `M-x term`.

**Comment by Compro-Prasad** [comment]
This can be controlled by setting some comint variable. Not sure what it is.
