### ISSUE TITLE
Default key prefix conflicts with recent projectile

### ISSUE THREAD

**Issue by r-darwish** [pwalsh/pipenv.el#38]
Recently, projectile [changed](https://github.com/bbatsov/projectile/commit/bc5a96cefb7a76361df17a0b8262152bfde220b5) their default prefix to from `C-c p` to `C-c C-p`

**Comment by nossralf** [comment]
This has since been changed and Projectile no longer defines a default prefix, so there is no conflict.

https://github.com/bbatsov/projectile/blob/master/projectile.el#L151

**Comment by pwalsh** [comment]
Thanks @nossralf - I just noticed this myself on upgrading Projectile.
