### ISSUE TITLE
(pipenv-executable-find "python") not working on Windows

### ISSUE THREAD

**Issue by bitsandscraps** [pwalsh/pipenv.el#40]
On Windows,
```lisp
(pipenv-executable-find "python")
```
is `nil` whereas
```lisp
(pipenv-executable-find "python.exe")
```
evaluates to the correct path. Is this intended?
Plus, now it looks like flycheck is working well even when `pipenv-with-flycheck` is set to `nil`.
I've tested it with Emacs 26.1 both on Ubuntu 18.04 and Windows 10.

**Comment by pwalsh** [comment]
Hi!

I know very little about development environments on Windows. I would assume this is intended. Happy for some help on this from Windows users.

**Comment by juergenhoetzel** [comment]
https://github.com/pwalsh/pipenv.el/pull/52 to check for the executable in a platform-agnostic way
