### ISSUE TITLE
Trailing color codes Issue

### ISSUE THREAD

**Issue by ztlevi** [pwalsh/pipenv.el#43]
The problem is I got tailing color code like `^[[0m` in the pipenv venv responses.

For example:
![](https://emacs-china.org/uploads/default/original/2X/8/86c843b89b81db589925fb4d968b9338380bd723.png)

In the case, it's not going to consider this response as a directory. A quick fix is:

```
  (defun pipenv--clean-response (response)
    "Clean up RESPONSE from shell command."
    (replace-regexp-in-string "\n\\[0m$" "" (s-chomp response)))
```

But maybe there are more color codes need to be deleted. And I don't know how to prevent this happening.

**Comment by pwalsh** [comment]
Fixed in https://github.com/pwalsh/pipenv.el/pull/47
