### ISSUE TITLE
Looking for a new maintainer

### ISSUE THREAD

**Issue by pwalsh** [pwalsh/pipenv.el#45]
Hi all,

I don't plan on continuing to work on pipenv.el.

The reason for this is that I am not using Pipenv anymore. Using Pipenv has been a pretty frustrating experience for me generally, and while I was excited about the potential for Python packaging, I find the implementation sub par, the dynamics on the Pipenv issue tracker not welcoming, and the original messaging about it implying it was *the* officially recommended Python packaging tool misleading.

I've simply moved over to [pip-tools](https://github.com/jazzband/pip-tools) which solidly works with no weird bugs for my use cases

I'm happy to transfer the repo to anyone interested in maintaining this package going forward.

**Comment by garyo** [comment]
Hi @pwalsh; I've been having the same frustrations with pipenv. I liked that it both pinned dependencies, and managed virtualenvs (though the subshell thing bothered me). If you've moved to pip-tools for pinning dependencies, what are you planning to use in emacs to manage virtualenvs (for exec-path and subshell PATH)?

**Comment by valignatev** [comment]
You're not alone on this one. I've moved to poetry.

**Comment by billwanjohi** [comment]
Totally understandable, and thanks for your contributions up to this point. May I suggest that you [learn from our node friends](https://news.ycombinator.com/item?id=18534392) and _don't_ grant any new maintainer permissions to your `pwalsh` namespace, but instead (optionally) point to a forked repository from here.

**Comment by inpefess** [comment]
I'm interested in (using and) moving this package forward.

**Comment by pwalsh** [comment]
@inpefess great! 

I suggest:

1. You fork this repo.
2. You make some changes as per the open tickets, and do 1-2 PRs into this repo that I can review.
3. Then, we you are sure you will continue maintaining, we communicate to Melpa, and visitors here, that your fork is now the official version.

Does that work, or, do you have an alternate suggestion?

**Comment by inpefess** [comment]
@pwalsh Yes, that's a working solution, I think.

**Comment by inpefess** [comment]
@pwalsh let's go through review https://github.com/pwalsh/pipenv.el/pull/47

**Comment by Yevgnen** [comment]
@valignatev Do you use poetry in Emacs?

**Comment by valignatev** [comment]
@Yevgnen Yes, I do. But without any Emacs plugin, I just set virsualenvs path to point to poetry, and then I perform all poetry operations from the terminal.

**Comment by pwalsh** [comment]
Hi everyone. Things were very quite here. I just unarchived the repo because @conao3 has asked to become maintainer. We will see how that goes for some time and if successful transfer the repo over.

**Comment by conao3** [comment]
I'm the new maintainer, conao3. If anyone have any problems, I hope you can report them here, as you have been doing in the past.
I think `pipenv` is the savior of Python and this project is needed to use `pipenv` from Emacs!

**Comment by conao3** [comment]
I'm here and I already have push permission, close for now. If anyone want help this work, please comment!
