### ISSUE TITLE
el-get recipe

### ISSUE THREAD

**Issue by Pitometsu** [pwalsh/pipenv.el#9]
Please, add to `Installation` subsection for [el-get](https://github.com/dimitri/el-get)

Here's recipe (until it not in recipes repository yet):

```elisp
(:name pipenv
       :type github
       :pkgname "pwalsh/pipenv.el"
       :description "Manage Pythons with Pipenv in Emacs."
       :depends (s f))
```

**Comment by pwalsh** [comment]
Hi @Pitometsu I've looked at the `el-get` readme, but, I do not use `el-get`, and a quick look does no help me understand how to install with it, nor how/where to use a recipe. I'm closing this as wontfix, but very happy to receive a pull request from an `el-get` user for this.

**Comment by Pitometsu** [comment]
Any `el-get` user would understend, how to use [this recipe](https://github.com/pwalsh/pipenv.el/issues/9#issue-290278316) if you just put it in readme. Or I can notify later, when it be in `el-get` repository to let el-get users just do `M-x el-get-install pipenv`..
